### ISSUE TITLE
Care to showcase your work on FreeCAD forums?

### ISSUE THREAD

**Issue by luzpaz** [wgaonar/elevador#1]
Specifically in the [User Showcase subforum](https://forum.freecadweb.org/viewforum.php?f=24) ?  
What you can talk about is your process, how you used FreeCAD. Things you love about FC, things you think need improvements, workarounds you used when encountering obstacles...etc...

**Comment by wgaonar** [comment]
Hello, It sounds great. There is no problem.

**Comment by wgaonar** [comment]
It is done.
